export const TOURNAMENTS = [
  {
    id: 'rookie-cup',
    name: 'Rookie Cup',
    difficulty: 'easy',
    icon: '🥉',
    description: 'Begin your journey',
    rewardCoins: 100,
    rewardXP: 50,
    requiredTrophies: 0,
    rounds: ['Round of 16', 'Quarter Final', 'Semi Final', 'Final'],
    goalsToAdvance: [2, 3, 3, 4],
    maxAttempts: 5,
  },
  {
    id: 'silver-shield',
    name: 'Silver Shield',
    difficulty: 'normal',
    icon: '🥈',
    description: 'Test your skills',
    rewardCoins: 250,
    rewardXP: 120,
    requiredTrophies: 1,
    rounds: ['Round of 16', 'Quarter Final', 'Semi Final', 'Final'],
    goalsToAdvance: [3, 3, 4, 4],
    maxAttempts: 5,
  },
  {
    id: 'gold-crown',
    name: 'Gold Crown',
    difficulty: 'hard',
    icon: '🥇',
    description: 'Prove your mastery',
    rewardCoins: 500,
    rewardXP: 300,
    requiredTrophies: 2,
    rounds: ['Round of 16', 'Quarter Final', 'Semi Final', 'Final'],
    goalsToAdvance: [3, 4, 4, 5],
    maxAttempts: 5,
  },
  {
    id: 'platinum-star',
    name: 'Platinum Star',
    difficulty: 'expert',
    icon: '⭐',
    description: 'Only the best survive',
    rewardCoins: 1000,
    rewardXP: 600,
    requiredTrophies: 3,
    rounds: ['Round of 16', 'Quarter Final', 'Semi Final', 'Final'],
    goalsToAdvance: [4, 4, 5, 5],
    maxAttempts: 5,
  },
  {
    id: 'legendary',
    name: 'Legendary Cup',
    difficulty: 'legendary',
    icon: '🏆',
    description: 'Become a legend',
    rewardCoins: 2500,
    rewardXP: 1500,
    requiredTrophies: 4,
    rounds: ['Round of 16', 'Quarter Final', 'Semi Final', 'Final'],
    goalsToAdvance: [4, 5, 5, 5],
    maxAttempts: 5,
  },
];

export const DIFFICULTY_SETTINGS = {
  easy: {
    keeperSpeed: 0.8,
    keeperReaction: 1.2,
    patrolRange: 100,
  },
  normal: {
    keeperSpeed: 1.0,
    keeperReaction: 1.0,
    patrolRange: 140,
  },
  hard: {
    keeperSpeed: 1.3,
    keeperReaction: 0.8,
    patrolRange: 180,
  },
  expert: {
    keeperSpeed: 1.5,
    keeperReaction: 0.7,
    patrolRange: 200,
  },
  legendary: {
    keeperSpeed: 1.8,
    keeperReaction: 0.6,
    patrolRange: 220,
  },
  god: {
    keeperSpeed: 2.2,
    keeperReaction: 0.4,
    patrolRange: 250,
  },
};
